runtime: nodejs10
instance_class: f1
automatic_scaling:
    max_instances: 1
env_variables:
  APP_ENGINE_QUEUE: timetrigger-queue
  LOCATION: us-central1
  NODE_ENV: production
  PROJECT_ID: timetrigger-5a192
