runtime: nodejs10
instance_class: f1
automatic_scaling:
    max_instances: 1
env_variables:
  API_HOST: https://timetrigger-5a192.appspot.com
  APP_ENGINE_QUEUE: timetrigger-queue
  LOCATION: us-central1
  NODE_ENV: production
  PROJECT_ID: timetrigger-5a192
  UUID_NAMESPACE: d224553b-52d9-45bd-bc5c-470c99b1449e
