import React from "react";
import Typography from "@material-ui/core/Typography";

export default function PrivacyPage({ classes }) {
  return (
    <div>
      <Typography paragraph variant="body1">We respect the confidentiality of your personal data and aim to protect them. Our privacy policy complies with European Regulation (EC) No 45/2001, as well as with Laws 2472/1997, 3471/2006 and 2819/2000, and Presidential Decrees 207/1998 and 79/2000 on the protection of personal data, as amended from time to time, as well as with any other applicable legislation.</Typography>
      <Typography paragraph variant="body1">We collect and keep with your consent and approval the personal data you provide us, including information such as your e-mail address. You own all your information and we do not collect, use or process any other information about you unless you have given us permission, or you have been notified by us.</Typography>
      <Typography paragraph variant="body1">We receive data about you each time you use the computer, mobile phone or other device in order to access Time Trigger, such as the pages you visit, the IP address, location, type of browser. We may receive data from our advertising partners, customers or third parties in order to improve the quality of our services to you.</Typography>
      <Typography paragraph variant="body1">In addition, we process data from your existing information relating to you to show you commercial content that might be relevant and interesting to you.</Typography>
      <Typography paragraph variant="body1">We respect the information we receive about you and use it to provide you our services, as well as provide the necessary services to the advertisers that purchase advertisements on Time Trigger and the developers of the applications, and websites you use.</Typography>
      <Typography paragraph variant="body1">You can delete, correct or amend your personal information at any time, by sending an e-mail at: <a href="mailto:support@timetrigger.com">support@timetrigger.com</a></Typography>
      <Typography paragraph variant="body1">We may provide your information if required by law and if deemed necessary to prevent any illegal activity or violation of any applicable laws of the Territory.</Typography>
      <Typography paragraph variant="body1">We use cookies only to gather the necessary information in order to provide to you our full services, in accordance with EU legislation on cookies, as in force and effect. You fully and unreservedly consent to such use by indicating your wish at a "cookie notice" page or pop-up window.</Typography>
      <Typography paragraph variant="body1">We give your information to the people and companies that help us provide the services we offer. In all of these cases our partners must agree to only use your information consistent with the agreement we enter into with them, as well as this privacy policy.</Typography>
      <Typography paragraph variant="body1">Any third parties, to whom we give your information in order to provide you our services, must agree with this privacy policy.</Typography>
      <Typography paragraph variant="body1">If the ownership of our business changes, we may transfer your information to the new owner so they can continue to operate the service. But they will still have to comply with the commitments we have made in this privacy policy.</Typography>
      <Typography paragraph variant="body1">This privacy policy remains valid and in full force and effect in case of change of ownership of Time Trigger and subsequent transfer of your information to the new owner.</Typography>
      <Typography paragraph variant="body1">We reserve our right to change the terms of this privacy policy at any time, with prior notification and within the existing or potential legal framework.</Typography>

      <Typography paragraph variant="h5">Cookies</Typography>
      <Typography paragraph variant="body1">We use cookies only to gather the necessary information in order to provide to you our full services, in accordance with EU legislation on cookies, as in force and effect. You fully and unreservedly consent to such use by indicating your wish at a “cookie notice” page or pop-up window. You can always delete your cookies following the process described by your browser. Based on the cookies we collect we may create advertising campaigns through Facebook, Instagram, YouTube or Google to display ads based on the pages you have visited in our website.</Typography>
      <Typography paragraph variant="subtitle2">Google Analytics & Adwords</Typography>
      <Typography paragraph variant="body1">We use Google Analytics and Adwords cookie in order to anonymously track user behavior in our website, gather important statistical information about our platform’s performance and retarget people with advertising campaigns based on how users have interacted with our platform. All information gathered is anonymous. Specifically the Google Adwords cookie measures the performance of our advertising campaigns on Google and Google Display network. You can delete the Google Analytics and Adwords cookie by visiting your browser settings.</Typography>
      <Typography paragraph variant="h5">Disclaimer</Typography>
      <Typography paragraph variant="body1">While we make every effort to ensure that the content of this website is accurate, the website is provided 'as is' and we make no representations or warranties in relation to the accuracy or completeness of the information provided.</Typography>
      <Typography paragraph variant="body1">Nothing on this website should be taken to constitute professional or legal advice or a formal recommendation and we exclude all representations and warranties relating to the content and use of this site. In no event will we be liable for any incidental, indirect, consequential or special damages of any kind, or any damages whatsoever, including, without limitation, those resulting from loss of profit, loss of contracts, goodwill, data, information, income, anticipated savings or business relationships, whether or not advised of the possibility of such damage, arising out of or in connection with the use of this website or any linked websites.</Typography>
      <Typography paragraph variant="body1">We do not warrant that the servers that make this website available will be error, virus or bug free and you accept that it is your responsibility to make adequate provision for protection against such threats. We recommend scanning any files before downloading.</Typography>
      <Typography paragraph variant="body1">Effective as of 1/20/2021.</Typography>
    </div>
  );
}
