import React from "react";
import Typography from "@material-ui/core/Typography";

export default function PrivacyPage() {
  return (
    <div>
      <Typography paragraph variant="body1">Please read carefully the following Terms (“Terms") which, together with the Privacy Policy, constitute a binding legal agreement (“Agreement”) between you (“you”), and the company Time Trigger ("Time Trigger", "timetrigger.dev", “Company”, “us”) and govern your access to and use of Company's platform (www.timetrigger.dev), unless you have entered into a separate agreement in writing with the Company regarding the access to and use of the platform, which (other agreement) prevails.</Typography>
      <Typography paragraph variant="h5">1. Formation of Agreement</Typography>
      <Typography paragraph variant="body1">www.timetrigger.dev is a web platform (“the Platform”) that offers an API to deliver point-in-time notifications/webhooks to your services. By using the platform [and/or by creating an account in the platform] you confirm that you agree to and are bound by the terms of the Agreement. In case of disagreement, you should refrain from visiting the website and from using its services.</Typography>
      <Typography paragraph variant="body1">You also represent and warrant that you are at least 18 years old and that all registration information you submit is accurate and truthful. Individuals under the age of 18 must at all times use our services only in conjunction with and under the supervision of a parent or legal guardian who is at least 18 years of age. In all cases, the adult is the user and is responsible for any and all activities.</Typography>
      <Typography paragraph variant="body1">If you register on behalf of a legal entity, you represent to the Company that you have the authority to bind that legal entity and that your acceptance of this Agreement will be treated as acceptance by that legal entity. In such event, “you” will refer and apply to that legal entity.</Typography>
      <Typography paragraph variant="body1">You agree to comply with all local laws regarding online conduct and acceptable content. You are responsible for all applicable taxes, as well as all any operating rules, policies and procedures that may be published from time to time on the site.</Typography>
      <Typography paragraph variant="h5">2. Prohibited, Questionable and Infringing Content and Activities</Typography>
      <Typography paragraph variant="body1">You are solely responsible for your conduct and activities on and regarding to the platform and any and all data, text, information, usernames, graphics, images, photographs, profiles, audio, video, items, and links (together, "Content") that you submit, post, and display on the platform.</Typography>
      <Typography paragraph variant="body1">Restricted Activities: Your Content and your use of the platform shall not:</Typography>
      <Typography paragraph variant="body1">
        <ul>
          <li>Be false, inaccurate or misleading</li>
          <li>Be fraudulent or involve the sale of illegal, counterfeit or stolen items</li>
          <li>Infringe upon any third-party's copyright, patent, trademark, trade secret or other proprietary or intellectual property rights or rights of publicity or privacy</li>
          <li>Be defamatory, trade libelous, unlawfully threatening, unlawfully harassing, impersonate or intimidate any person, or falsely state or otherwise misrepresent your affiliation with any person, through for example, the use of similar email address, nicknames, or creation of false account(s) or any other method or device</li>
          <li>Be obscene or contain child pornography</li>
          <li>Contain or transmit any code of a destructive nature that may damage, detrimentally interfere with, surreptitiously intercept or expropriate any system, data or personal information</li>
          <li>Modify, adapt or hack the Platform or modify another website so as to falsely imply that it is associated with the Platform;</li>
        </ul>
      </Typography>
      <Typography paragraph variant="h5">3. Content and proprietary rights</Typography>
      <Typography paragraph variant="body1">The content, the form and the services of this website are property of the Company and its affiliates or licensors. The sale, copy, modification, reproduction, lease, rental, loan, distribution or creation of derivative works based on the above content, in whole or in part is prohibited. The Company’s graphics, logos, designs, page headers, button icons, scripts, and service names are registered trademarks, trademarks of the Company and may not be used without prior Company’s license, including as part of trademarks and/or as part of domain names or email addresses, in connection with any product or service in any manner that is likely to cause confusion.</Typography>
      <Typography paragraph variant="body1">On the other hand, the present Agreement does not imply any transfer of copyright or intellectual property rights on the content provided by you, to the Company. The Company does not claim any ownership rights on content, and you hereby expressly acknowledge and agree that your content remains your sole responsibility.</Typography>
      <Typography paragraph variant="body1">You do declare that your content does not and will not create any liability on the part of the Company, its subsidiaries, affiliates, successors, and assigns, and their respective employees, agents, directors, officers and/or shareholders. Any unauthorized use of protected material within the content may constitute an infringement of third party rights and is strictly prohibited. In case any such claim arises, you declare and agree that you assume the entire responsibility and you will hold the Company and its officers, directors, licensees and employees harmless form any claim or demand made by a third party, and will fully indemnify them for any and all direct and indirect damages they may suffer.</Typography>
      <Typography paragraph variant="h5">4. Amendments</Typography>
      <Typography paragraph variant="body1"><strong>4.1</strong> The Company reserves the right, at its sole discretion, to modify the present Agreement at any time. Such changes will become effective immediately after they have been posted to our website, or the Company has otherwise notified you of the change. By continuing to access or use the services after we have posted a modification to the Terms or have provided you with notice of a modification, you are indicating that you agree to be bound by the modified Terms. If the modified Terms are not acceptable to you, your only recourse is to cease using the services and, if applicable, cancel your Account.</Typography>
      <Typography paragraph variant="body1"><strong>4.2</strong> The Company also reserves the right to change, modify, withdraw or discontinue any of the features, services and functionalities of the entire website www.timetrigger.dev at any time and for any reason without prior notice.</Typography>
      <Typography paragraph variant="body1"><strong>4.3</strong> You hereby agree that the Company and its subsidiaries, affiliates, successors, assigns, employees, agents, directors, officers and shareholders shall not be liable to you or to any third party for any changes or modifications to the website and/or the services provided, or for any decision to suspend, discontinue or terminate the website, the services or any part or parts thereof, or your possibility to use or access the same from or within any territory or territories.</Typography>
      <Typography paragraph variant="h5">5. Personal data</Typography>
      <Typography paragraph variant="body1">By entering into the present Agreement you declare that the personal data you have entered when creating an account are accurate, current, and complete and that you will update such information to keep it accurate, current, and complete. The Company has no liability for failure to deliver notices that result from inaccurate account information or otherwise. You also declare that the Company has the right to collect, store, process, use and disclose part or all of such information, in accordance with the Privacy Policy.</Typography>
      <Typography paragraph variant="h5">6. Assignment</Typography>
      <Typography paragraph variant="body1">The Company may assign this Agreement and part or all of the rights and obligations arising thereof, to any third party, individual or legal entity, in The United States of America or abroad, without restrictions.</Typography>
      <Typography paragraph variant="h5">7. No warranty - Limitation of liability</Typography>
      <Typography paragraph variant="body1">The use of the platform as well as of any related application is at your own risk. The Platform is provided on an “as is” and “as available” basis. To the fullest extent possible under applicable law, the Company gives no warranty, express or implied, as to the quality, content and availability or fitness for a specific purpose of the platform.</Typography>
      <Typography paragraph variant="body1">In no event shall the Company, its affiliates, officers, directors, employees, licensees or any third parties be liable for any direct, indirect, incidental, special or consequential damages (including but not limited to any loss of data, service interruption, computer failure or pecuniary loss) arising out of the use of or inability to use the Platform.</Typography>
      <Typography paragraph variant="h5">8. External content</Typography>
      <Typography paragraph variant="body1">The Platform may contain referrals through links, hyperlinks or advertising banners to third party websites. The availability, content, personal data protection policy, quality and integrity of services of these websites is not subject to the control of the Company. We do not bear any liability whatsoever for the content and functions of any third party website, which are available to the user via links, hyperlinks or banners.</Typography>
      <Typography paragraph variant="body1">The user expressly and unconditionally accepts that the Company shall not be liable for any loss or damage, direct or indirect, regardless of the specific cause, the name and form, resulting from the availability of the above third party websites or resources, or resulting from any trust exhibited in the integrity, accuracy or existence of any advertising, product or other material contained or available on the above websites or resources.</Typography>
      <Typography paragraph variant="h5">9. Final provisions</Typography>
      <Typography paragraph variant="body1">The user expressly and unconditionally accepts that the Company shall be able to place and/or show advertisements in the scope of this website.</Typography>
      <Typography paragraph variant="body1">Without limiting any other remedies, the Company may, without notice, and without refunding any fees, delay or immediately remove Content, issue a warning to a user, temporarily suspend a user, temporarily or indefinitely suspend a user's account privileges, terminate a user's account, prohibit access to the site, and take technical and legal steps to keep a user off the site and refuse to provide services to a user.</Typography>
      <Typography paragraph variant="body1">The failure of the Company to exercise or enforce any right or provision of the Terms shall not constitute a waiver of such right or provision.</Typography>
      <Typography paragraph variant="body1">It is explicitly agreed that the present Agreement is valid also in case of change in the Company’s form, registered offices, etc., as long as the legal entity remains the same, as well as in case of assignment.</Typography>
      <Typography paragraph variant="body1">Should any of the terms of the present Agreement be held invalid or unenforceable by a court for any whatsoever reason, the parties nevertheless agree that the court should endeavor to give effect to the parties' intentions as reflected in the provision, and such invalidity or unenforceability shall not affect or render invalid the remaining provisions of this Agreement.</Typography>
      <Typography paragraph variant="body1">This Agreement shall be governed and construed by the laws of The United States of America. Any dispute, controversy or claim arising out of or in connection with the present Agreement will be subject to the exclusive jurisdiction of the Courts of South Orange, NJ, USA.</Typography>
      <Typography paragraph variant="h5">Contact Us</Typography>
      <Typography paragraph variant="body1">If you have any questions about the present Terms of Use / Service, please contact us at: <a href="mailto:support@timetrigger.dev">support@timetrigger.dev</a></Typography>
      <Typography paragraph variant="body1">Effective 1/20/2021</Typography>
    </div>
  );
}
